# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(722, 269)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 10, 431, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Time_duplicate = QtWidgets.QTextEdit(self.centralwidget)
        self.Time_duplicate.setGeometry(QtCore.QRect(20, 110, 201, 41))
        self.Time_duplicate.setReadOnly(True)
        self.Time_duplicate.setObjectName("Time_duplicate")
        self.row_duplicate = QtWidgets.QTextEdit(self.centralwidget)
        self.row_duplicate.setGeometry(QtCore.QRect(260, 110, 91, 41))
        self.row_duplicate.setReadOnly(True)
        self.row_duplicate.setObjectName("row_duplicate")
        self.column_duplicate = QtWidgets.QTextEdit(self.centralwidget)
        self.column_duplicate.setGeometry(QtCore.QRect(390, 110, 91, 41))
        self.column_duplicate.setReadOnly(True)
        self.column_duplicate.setObjectName("column_duplicate")
        self.serial_duplicate = QtWidgets.QTextEdit(self.centralwidget)
        self.serial_duplicate.setGeometry(QtCore.QRect(520, 110, 151, 41))
        self.serial_duplicate.setReadOnly(True)
        self.serial_duplicate.setObjectName("serial_duplicate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 80, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(420, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 80, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.Confirm_ignore = QtWidgets.QPushButton(self.centralwidget)
        self.Confirm_ignore.setEnabled(False)
        self.Confirm_ignore.setGeometry(QtCore.QRect(260, 180, 151, 51))
        self.Confirm_ignore.setObjectName("Confirm_ignore")
        self.Auto_check_box = QtWidgets.QCheckBox(self.centralwidget)
        self.Auto_check_box.setEnabled(True)
        self.Auto_check_box.setGeometry(QtCore.QRect(50, 190, 101, 31))
        self.Auto_check_box.setChecked(True)
        self.Auto_check_box.setObjectName("Auto_check_box")
        self.manual_check = QtWidgets.QPushButton(self.centralwidget)
        self.manual_check.setEnabled(False)
        self.manual_check.setGeometry(QtCore.QRect(560, 180, 111, 41))
        self.manual_check.setObjectName("manual_check")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Duplicate Detection Software"))
        self.label.setText(_translate("MainWindow", "Tracking Duplicate Issue for GammaSU "))
        self.label_2.setText(_translate("MainWindow", "Thời gian trùng"))
        self.label_3.setText(_translate("MainWindow", "Hàng"))
        self.label_4.setText(_translate("MainWindow", "Cột"))
        self.label_5.setText(_translate("MainWindow", "Serial Duplicate"))
        self.Confirm_ignore.setText(_translate("MainWindow", "Loại bỏ con hàng trùng"))
        self.Auto_check_box.setText(_translate("MainWindow", "AUTO CHECK"))
        self.manual_check.setText(_translate("MainWindow", "MANUAL CHECK "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
